In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

# 第一題：
題目：給定一個矩陣m，裡面的值都大於0。
請將矩陣m裡大於等於1的數字都變成1，小於1的變成0。
 
m = np.array([[0,1,10],[2,6,7]])
 
提示：使用巢狀迴圈(nested loop)加判斷式

In [2]:
m = np.array([[0,1,10],[2,6,7]])

In [3]:
m

array([[ 0,  1, 10],
       [ 2,  6,  7]])

In [6]:
m[m>=1]

array([ 1, 10,  2,  6,  7])

In [29]:
result = []
m.shape = (6,1)
for i in m:
    if i >=1:
        result.append(1)
    else:
        result.append(0)
result = np.array(result)
result.shape = (2,3)
result

array([[0, 1, 1],
       [1, 1, 1]])

# 第二題：
有A,B,C三個班級，每班皆有10個學生，期中考結束後，老師希望計算各班級每位學生的加權平均成績。
 
請隨機產生3個班級的成績單,每班10人,共五科,權重為weights=[0.25,0.25,0.25,0.15,0.10]。
請算出班級加權平均成績，並以一個array輸出。

In [60]:
#隨機產生3個班級的成績
A = np.random.randint(0,101,50)
B = np.random.randint(0,101,50)
C = np.random.randint(0,101,50)
A.shape = (10,5)
B.shape = (10,5)
C.shape = (10,5)
#權重
weights=[0.25,0.25,0.25,0.15,0.10]

In [63]:
A_grades = np.dot(A,weights)
B_grades = np.dot(B,weights)
C_grades = np.dot(C,weights)

In [95]:
fin_A_grades = sum(A_grades)/10
fin_B_grades = sum(B_grades)/10
fin_C_grades = sum(C_grades)/10

In [96]:
allclass = []
allclass.append(fin_A_grades)
allclass.append(fin_B_grades)
allclass.append(fin_C_grades)

In [99]:
allclass = np.array(allclass)
allclass

array([ 46.535,  51.71 ,  49.185])

# 挑戰題一：
請定義一個全班高微成績的函式，輸入是一個(3, 30, 3)的array，  
表示3個班級中30位學生的成績(小考，期中考，期末考)  。

目標輸出則是一個(3, 30, 1)的array，表示所有學生的期末成績，
期末成績計算方式如下：

1. 小考20%，期中考35%，期末考45%  
2. 期中考40%，期末考60%。  
擇優作為期末成績
 
Hint
* 可以用雙重for迴圈 分別跑過班級跟人
* 可以先設一個array裝算出來的成績
* 記得要用return 
* 請做個測試，檢驗你的結果，方便同學評分。

In [125]:
def grade():
    classgrade = []
    while len(classgrade) < 3:
        student = []
        while len(student) < 30:
            person = []
            while len(person) < 3:
                a = input("小考成績： ")
                person.append(a)
                b = input("期中考成績： ")
                person.append(b)
                c = input("期末考成績： ")
                person.append(c)
                student.append(person)
            classgrade.append(student)

In [165]:
def math_grade():
    classgrade = []
    while len(classgrade) < 3:
        student = []
        while len(student) < 30:
            person = []
            while len(person) < 3:
                a = input("小考成績： ")
                person.append(a)
                b = input("期中考成績： ")
                person.append(b)
                c = input("期末考成績： ")
                person.append(c)
                student.append(person)
            classgrade.append(student)
            classgrade = np.array(classgrade)
    for i in range(3):
        for j in range(30):
            a = classgrade[i][j]
            a_plan = np.dot(a,plan_a)
            b_plan = np.dot(b,plan_b)
            fin_person = []
            while len(fin_person) < 30:
                if a_plan >= b_plan:
                    fin_person.append(a_plan)
                else:
                    fin_person.append(b_plan)
        fin_class = []
        while len(fin_class) < 3:
            fin_class.append(fin_person)
    fin_class = np.array(fin_class)
    fin_class
    
            

In [166]:
math_grade()

小考成績： 50
期中考成績： 60
期末考成績： 100
小考成績： 20
期中考成績： 0
期末考成績： 30
小考成績： 50
期中考成績： 80
期末考成績： 90
小考成績： 90
期中考成績： 100
期末考成績： 100
小考成績： 20
期中考成績： 30
期末考成績： 30
小考成績： 30
期中考成績： 40
期末考成績： 50
小考成績： 50
期中考成績： 60
期末考成績： 60
小考成績： 61
期中考成績： 78
期末考成績： 68
小考成績： 90
期中考成績： 86
期末考成績： 88
小考成績： 85
期中考成績： 95
期末考成績： 100
小考成績： 56
期中考成績： 62
期末考成績： 34
小考成績： 55
期中考成績： 75
期末考成績： 88
小考成績： 85
期中考成績： 66
期末考成績： 99
小考成績： 100
期中考成績： 99
期末考成績： 44
小考成績： 80
期中考成績： 80
期末考成績： 80
小考成績： 90
期中考成績： 90
期末考成績： 90
小考成績： 90
期中考成績： 90
期末考成績： 909
小考成績： 100
期中考成績： 20
期末考成績： 100
小考成績： 100
期中考成績： 100
期末考成績： 20
小考成績： 0
期中考成績： 30
期末考成績： 20
小考成績： 50
期中考成績： 50
期末考成績： 505
小考成績： 50
期中考成績： 50
期末考成績： 50
小考成績： 50
期中考成績： 50
期末考成績： 505
小考成績： 50
期中考成績： 50
期末考成績： 10
小考成績： 10
期中考成績： 10
期末考成績： 10
小考成績： 10
期中考成績： 10
期末考成績： 10
小考成績： 10
期中考成績： 10
期末考成績： 10
小考成績： 10
期中考成績： 10
期末考成績： 10
小考成績： 20
期中考成績： 20
期末考成績： 20
小考成績： 20
期中考成績： 20
期末考成績： 20


TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'

In [221]:
plan_a = np.array([0.2,0.35,0.45])
plan_b = np.array([0,0.4,0.6])
test = np.array([[[30,40,50],[60,90,50]],
                 [[90,90,90],[60,66,60]],
                 [[100,20,80],[50,20,30]]])
for i in range(0,3) :
    a = test[i]
    for j in range(0,2) :
        a_plan = np.dot(a[j],plan_a)
        b_plan = np.dot(a[j],plan_b)
        if a_plan >= b_plan:
            fin_person = np.array([a_plan])
        else:
            fin_person = np.array([b_plan])
        fin_class = []
        while len(fin_class) < 2:
            fin_class.append(fin_person)
    fin = []
    while len(fin) < 3:
        fin.append(fin_class)    
fin = np.array(fin)
fin

array([[[ 30.5],
        [ 30.5]],

       [[ 30.5],
        [ 30.5]],

       [[ 30.5],
        [ 30.5]]])

In [193]:
    for i in range(3):
        for j in range(30):
            a = classgrade[i][j]
            a_plan = np.dot(a,plan_a)
            b_plan = np.dot(a,plan_b)
            fin_person = []
            while len(fin_person) < 30:
                if a_plan >= b_plan:
                    fin_person.append([a_plan])
                else:
                    fin_person.append([b_plan])
        fin_class = []
        while len(fin_class) < 3:
            fin_class.append([fin_person])
    fin_class = np.array(fin_class)
    fin_class

TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'

In [225]:
test = np.array([[[30,40,50],[60,90,50]],
                 [[90,90,90],[60,66,60]],
                 [[100,20,80],[50,20,30]]])
for i in range(0,3) :
    a = test[i]

[[30 40 50]
 [60 90 50]]
[[90 90 90]
 [60 66 60]]
[[100  20  80]
 [ 50  20  30]]


In [226]:
a = [30 40 50]

SyntaxError: invalid syntax (<ipython-input-226-0a572cab2892>, line 1)